name: Deploy Munki Infrastructure

on:
  push:
    branches: [main]
    paths:
      - '*.tf'
      - 'modules/**'
  workflow_dispatch:

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

jobs:
  terraform:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.x

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ env.ARM_CLIENT_ID }}
          tenant-id: ${{ env.ARM_TENANT_ID }}
          subscription-id: ${{ env.ARM_SUBSCRIPTION_ID }}

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="resource_group_name=Terraform" \
            -backend-config="storage_account_name=tfstate" \
            -backend-config="container_name=state" \
            -backend-config="key=munki.tfstate"

      - name: Terraform Plan
        id: plan
        run: |
          terraform plan \
            -lock=true -out=tfplan \
            -var="azure_tenant_id=${{ secrets.AZURE_TENANT_ID }}" \
            -var="devops_group_object_id=${{ secrets.DEVOPS_GROUP_ID }}" \
            -var="munki_username=${{ secrets.MUNKI_USERNAME }}" \
            -var="munki_password=${{ secrets.MUNKI_PASSWORD }}" \
            -var="munki_client_token=${{ secrets.MUNKI_CLIENT_TOKEN }}" \
            -detailed-exitcode || echo "exitcode=$?" >> $GITHUB_OUTPUT

      - name: Terraform Apply
        if: steps.plan.outputs.exitcode == '2'
        run: terraform apply -auto-approve tfplan
